### ISSUE TITLE
sound_engine/voice.h:32:10: fatal error: Chorus.h: No such file or directory

### ISSUE THREAD

**Issue by nick87720z** [davy7125/polyphone#96]
This error effects both git and rel-2.2 versions. But it doesn't present in 2.1.
Context:
```
g++ -c -pipe -std=c++11 -O2 -pthread -pthread -Wall -W -D_REENTRANT -fPIC -DSOFT_VERSION=\"2.2.0\" -DIDENTIFIER=\"\" -D__LINUX_ALSASEQ__ -D__UNIX_JACK__ -DSFTOOLS_NOXML -D__LITTLE_ENDIAN__ -D__RTMIDI_DEBUG__ -D__LINUX_ALSA__ -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Ilib/qtsingleapplication -I/usr/local/include/jack -Ilib/flac -I/usr/local/include/stk -I/usr/local/include/qcustomplot -Imainwindow -Idialogs -Icontext -Icontext/interface -Ieditor -Ieditor/graphics -Ieditor/modulator -Ieditor/overview -Ieditor/tools -Ieditor/widgets -Ieditor/tree -Iqcustomplot -Iresources -Icore -Icore/input -Icore/output -Icore/model -Icore/sample -Icore/types -Iclavier -Isound_engine -Isound_engine/elements -Ilib/sf3 -Irepository -Irepository/browser -Irepository/daily -Irepository/widgets -Irepository/user -Irepository/soundfont -Irepository/soundfont/viewer -Irepository/soundfont/editor -I. -Ilib/sfarklib -isystem /usr/include/alsa -isystem /usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -isystem /usr/include/rtmidi -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtPrintSupport -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o contextmanager.o context/contextmanager.cpp
In file included from sound_engine/soundengine.h:30:0,
                 from sound_engine/synth.h:29,
                 from context/contextmanager.cpp:26:
sound_engine/voice.h:32:10: fatal error: Chorus.h: No such file or directory
 #include "Chorus.h"
          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:6405: contextmanager.o] Error 1
```

**Comment by hfiguiere** [comment]
PR #100 should fix this.

**Comment by davy7125** [comment]
I just commited similar things in https://github.com/davy7125/polyphone/commit/edbf068f28bbd7f972cd92d0d46dd080df7178c9

All files are correctly detected.

**Comment by john-davies** [comment]
Note that this fault still exists in the source code downloaded from the web page - https://www.polyphone-soundfonts.com/download. Latest GitHub is fine.

Maybe the web page should just redirect to the GitHub repository?

**Comment by Axel-Erfurt** [comment]
same error in Linux Mint 20.3 and polyphone 2.3 github version

```In file included from main.cpp:42:
sound_engine/voice.h:32:10: fatal error: stk/Chorus.h: Datei oder Verzeichnis nicht gefunden
   32 | #include "stk/Chorus.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
```

**Comment by Axel-Erfurt** [comment]
I solved it like this and was able to create it.

changed line 32 in  sources/voice.h

from
```#include "stk/Chorus.h"```
to
```#include "lib/_option_stk/stk/Chorus.h"```
